name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: pip install -r https://raw.githubusercontent.com/wgulw/Deploying-a-Scalable-ML-Pipeline-with-FastAPI/main/requirements.txt

      - name: Run pytest
        run: pytest python local_api.py

      - name: Run flake8
        run: flake8
