name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'  # Match this to your development Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      - name: Run flake8
        run: flake8 .

      - name: Run pytest
        run: pytest
